# Generated by Django 5.2.8 on 2025-12-17 05:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_admin', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_problem_sets', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('like_users', models.ManyToManyField(blank=True, related_name='liked_problem_sets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '문제집',
                'verbose_name_plural': '문제집 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlaySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_problems', models.PositiveIntegerField(default=10)),
                ('solved_count', models.PositiveIntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expired', models.BooleanField(default=False)),
                ('selected_problems', models.ManyToManyField(blank=True, related_name='play_sessions', to='questions.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='play_sessions', to=settings.AUTH_USER_MODEL)),
                ('problem_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='play_sessions', to='game.problemset')),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('problem_sets', models.ManyToManyField(blank=True, related_name='maps', to='game.problemset')),
            ],
        ),
        migrations.CreateModel(
            name='ProblemSetQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.problem')),
                ('problem_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.problemset')),
            ],
            options={
                'unique_together': {('problem_set', 'problem')},
            },
        ),
        migrations.AddField(
            model_name='problemset',
            name='problem',
            field=models.ManyToManyField(related_name='problem_sets', through='game.ProblemSetQuestion', to='questions.problem'),
        ),
        migrations.CreateModel(
            name='SessionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_answer', models.IntegerField()),
                ('is_correct', models.BooleanField()),
                ('response_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('solved_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='questions.problem')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='game.playsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '문제 풀이 로그',
                'verbose_name_plural': '문제 풀이 로그들',
                'ordering': ['-solved_at'],
                'unique_together': {('session', 'problem')},
            },
        ),
    ]
