# Generated by Django 5.2.8 on 2025-12-21 03:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sessionlog',
            index=models.Index(fields=['user', '-solved_at'], name='idx_log_user_time'),
        ),
        migrations.AddIndex(
            model_name='sessionlog',
            index=models.Index(fields=['user', 'is_correct', '-solved_at'], name='idx_log_user_wrong_time'),
        ),
        migrations.AddIndex(
            model_name='sessionlog',
            index=models.Index(fields=['session'], name='idx_log_session'),
        ),
        migrations.AddIndex(
            model_name='sessionlog',
            index=models.Index(fields=['problem'], name='idx_log_problem'),
        ),
    ]
