# Generated by Django 5.2.8 on 2025-12-21 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_profile_username_profile_nickname_userstats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='total_experience',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
